language: android

jdk:
  - oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.1
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

cache: false
sudo: required

before_install:
- chmod +x gradlew
- set -ex
- gem install fir-cli

script:
- "./gradlew dependencies || true"
- "./gradlew assembleDebug"

after_success:
- fir p app/build/outputs/apk/app-debug.apk -T ${FIR_TOKEN} -c "Upload by Travis CI - ${TRAVIS_BUILD_NUMBER}"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${ACCESS_TOKEN}
  file:
    - app/build/outputs/apk/app-debug.apk
  on:
    tags: true
    all_branches: true
